update Dockerfile to build vsc plugin
eclipse/kiso-testing pull request #12
Opened 2022-01-24 15:23 UTC by Pog3k

Add node and npm to the docker container..

2022-01-25 14:18 UTC, sebastianpfischer requested changes
Can you specify which parts are for the python and which parts are for the vsc? The idea is to cluster them and if we need to modify anything in the future to know what does it influence.

2022-01-25 17:03 UTC, kakooloukia requested changes

2022-01-25 17:03 UTC, kakooloukia commented on ci/Dockerfile
>  RUN chmod -R 777 ${HOME}
Same here:

RUN python3 -m pip install pipenv && chmod -R 777 ${HOME}

2022-01-26 10:18 UTC, Pog3k commented on ci/Dockerfile
> +
done

2022-01-26 10:18 UTC, Pog3k commented on ci/Dockerfile
>  RUN chmod -R 777 ${HOME}
done

2022-01-28 15:02 UTC, Pog3k commented
had to add some packages for the unittest. 
unittest will now run in a virtual frame buffer

2022-01-31 13:29 UTC, sebastianpfischer approved these changes

2022-01-31 14:03 UTC, kakooloukia approved these changes

2022-02-07 08:51 UTC, merged