feat: update to new release 0.15
eclipse/kiso-testing pull request #13
Opened 2022-02-07 15:12 UTC by Pog3k

Everything except Docs. Will be done in another PR

2022-02-10 07:51 UTC, sebclrsn requested changes

2022-02-10 07:51 UTC, sebclrsn commented on src/pykiso/test_coordinator/test_result.py
> +test_result
Previous header should be restored

2022-02-10 07:51 UTC, sebclrsn commented on tests/test_cc_pcan_can.py
> +    mocker, mock_can_bus, raw_data, can_id, cc_receive_param, expected_type
mock_PCANBasic fixture is needed everywhere, otherwise the tests will fail

2022-02-10 09:41 UTC, kakooloukia requested changes

2022-02-10 09:41 UTC, kakooloukia commented on examples/test_record/test_recorder_example.py
> +# Copyright (c) 2010-2021 Robert Bosch GmbH
# Copyright (c) 2010-2022 Robert Bosch GmbH
to be updated every where (VS code could help you there ;) )

2022-02-10 12:30 UTC, sebclrsn approved these changes

2022-02-11 12:56 UTC, sebastianpfischer approved these changes

2022-02-11 13:33 UTC, merged