fix: tag selection
eclipse/kiso-testing pull request #205
Opened 2022-12-06 17:06 UTC by Pog3k

2022-12-08 08:51 UTC, sebclrsn requested changes

2022-12-08 08:51 UTC, sebclrsn commented on src/pykiso/test_coordinator/test_execution.py
> +            )
```suggestion
            mod_usr_tags = {
                key.replace(character, ""): value
                for key, value in mod_usr_tags.items()
            }
```

2022-12-08 08:51 UTC, sebclrsn commented on src/pykiso/test_coordinator/test_execution.py
> +            )
```suggestion
            test_case.tag = {
                key.replace(character, ""): value
                for key, value in test_case.tag.items()
            )
```

2022-12-12 08:06 UTC, Pog3k commented on src/pykiso/test_coordinator/test_execution.py
> +            )
done

2022-12-12 08:06 UTC, Pog3k commented on src/pykiso/test_coordinator/test_execution.py
> +            )
done

2022-12-12 12:36 UTC, sebastianpfischer requested changes

2022-12-12 12:36 UTC, sebastianpfischer commented on src/pykiso/test_coordinator/test_execution.py
> +        if test_case.tag is None:
This needs to be well unittested (codecov complains)

2022-12-13 15:01 UTC, sebclrsn approved these changes

2022-12-14 15:41 UTC, sebastianpfischer approved these changes

2022-12-14 15:47 UTC, merged