feat: add step report folding
eclipse/kiso-testing pull request #221
Opened 2023-01-09 13:02 UTC by Pog3k

Tests are now foldable items.
If tests have failed they are open by default.

Also removed whitespaces when html gets generated

2023-01-09 16:14 UTC, sebclrsn requested changes

2023-01-09 16:14 UTC, sebclrsn commented on src/pykiso/test_result/assert_step_report.py
> +    return not any([not step["succeed"] for step in test])
```suggestion
    return all(step["succeed"] for step in test)
```
This seems equivalent and more readable

2023-01-10 15:58 UTC, sebclrsn approved these changes

2023-01-10 16:09 UTC, BKaDamien approved these changes

2023-01-11 07:56 UTC, merged