feat: add uptime for pcan inside python-can
eclipse/kiso-testing pull request #29
Opened 2022-03-01 14:30 UTC by Pog3k

will add uptime library for pcan timestamp

* changelog tool currently broke so ignore Changelog

2022-03-03 06:46 UTC, sebastianpfischer requested changes
I'm not sure, can you explain a little bit more what happened upstream that we need to add pcan this way? Before it was in the may library no?

2022-03-03 14:17 UTC, sebclrsn approved these changes

2022-03-04 09:57 UTC, Pog3k commented
> I'm not sure, can you explain a little bit more what happened upstream that we need to add pcan this way? Before it was in the may library no?

Actually its an ugly solution in python-can. I think it was never in python-can by default.
In the older version the just didn't print the import error.

See:
https://github.com/hardbyte/python-can/blob/develop/setup.py 
    "pcan": ["uptime~=3.0.1"], 
https://github.com/hardbyte/python-can/pull/1093

2022-03-07 08:45 UTC, kakooloukia approved these changes

2022-03-07 12:50 UTC, sebastianpfischer approved these changes

2022-03-07 12:51 UTC, merged