refactor: resolved codefactor issues [ready for review]
eclipse/kiso-testing pull request #307
Opened 2023-06-05 13:27 UTC by flo117

2023-06-09 08:31 UTC, sebastianpfischer approved these changes

2023-06-09 08:31 UTC, sebastianpfischer commented
We just need the jobs to be green and I'm fine to merge it

2023-06-13 13:55 UTC, sebclrsn requested changes

2023-06-13 13:55 UTC, sebclrsn commented on ci/Dockerfile
> +    && python3 -m pip install --no-cache-dir west \
```suggestion
# Install python packages. pip cache disabled to reduce docker image size.
RUN python3 -m pip install --no-cache-dir poetry tox west 
```
Can be done in one line :)

2023-06-13 13:55 UTC, sebclrsn commented on src/pykiso/tool/pykiso_to_pytest/cli.py
> +    # Autoexcape needs to be switched off, since executable python code is included which falsely triggers the issue.
```suggestion
    # Autoescape needs to be switched off, since executable python code is included which falsely triggers the issue.
```

2023-06-14 06:58 UTC, sebclrsn approved these changes

2023-06-19 14:09 UTC, merged