feat: make release 0.23.0
eclipse/kiso-testing pull request #327
Opened 2023-07-03 13:15 UTC by TedRio

2023-07-03 13:39 UTC, sebastianpfischer requested changes
Please also fix the readthedoc issue

2023-07-03 13:39 UTC, sebastianpfischer commented on docs/whats_new/version_0_23_0.rst
Please move the content of 0.22.2 to 0.23.0

2023-07-05 08:14 UTC, sebastianpfischer approved these changes

2023-07-05 09:18 UTC, Pog3k approved these changes

2023-07-05 09:19 UTC, merged