Feature/add uds responses timing evaluation **Not to be merge before python uds 3.1.0***
eclipse/kiso-testing pull request #353
Opened 2023-08-17 14:55 UTC by TedRio

2023-08-28 13:51 UTC, Pog3k commented
Update   pykiso-python-uds  in toml and lockfile

2023-08-28 14:10 UTC, Pog3k requested changes

2023-08-28 14:10 UTC, Pog3k commented on src/pykiso/lib/auxiliaries/udsaux/common/uds_response.py
> +            return "No data."
```suggestion
            return f"{self.__class__.__name__} no data."
```

2023-08-28 15:02 UTC, TedRio commented
> Update pykiso-python-uds in toml and lockfile

still waiting for python uds 3.1.0 deployment

2023-08-29 06:47 UTC, Pog3k commented
> > Update pykiso-python-uds in toml and lockfile
> 
> still waiting for python uds 3.1.0 deployment

I thought this is automatically done, anyways i triggered the build

2023-08-29 08:14 UTC, Pog3k approved these changes

2023-08-29 11:34 UTC, yannpoupon commented on src/pykiso/lib/auxiliaries/udsaux/common/uds_response.py
> +        :param pending_resp_times: list of the times between each response pending, in senconds
```suggestion
        :param pending_resp_times: list of the times between each response pending, in seconds
```

2023-08-29 11:34 UTC, yannpoupon commented on src/pykiso/lib/auxiliaries/udsaux/uds_auxiliary.py
> +        resp_print = (
Why do you not use the representation here instead of the format ?

2023-08-29 11:34 UTC, yannpoupon commented on src/pykiso/lib/auxiliaries/udsaux/uds_auxiliary.py
> +    def check_max_pending_time(resp: UdsResponse, max_pending_time: float):
```suggestion
    def check_max_pending_time(resp: UdsResponse, max_pending_time: float) -> bool:
```

2023-08-29 12:02 UTC, yannpoupon commented on src/pykiso/lib/auxiliaries/udsaux/uds_auxiliary.py
> +        log.internal_info(repr(resp))
```suggestion
        log.internal_info("UDS response received %s", resp)
To keep the same message

2023-08-29 12:08 UTC, yannpoupon commented on src/pykiso/lib/auxiliaries/udsaux/uds_auxiliary.py
> +To keep the same message
```suggestion
```

2023-08-29 12:10 UTC, yannpoupon approved these changes

2023-08-29 13:25 UTC, merged

2023-08-30 11:58 UTC, sebastianpfischer commented on step_report.html
Why was this added?