feat: give all connectors a name
eclipse/kiso-testing pull request #371
Opened 2023-09-26 14:38 UTC by DianeMornas

2023-09-27 06:06 UTC, sebastianpfischer approved these changes

2023-09-27 07:26 UTC, TedRio approved these changes

2023-09-27 11:06 UTC, Pog3k commented
you need also to assign a default name to all our existing connectores.
Otherwise the name attribute from  class Connector will always be None

2023-09-27 11:06 UTC, Pog3k requested changes
Give all existing connectors a name.. Otherwise it will always print None ?!

2023-09-29 10:28 UTC, sebclrsn approved these changes

2023-09-29 10:59 UTC, Pog3k approved these changes

2023-10-02 11:13 UTC, merged

2023-10-25 13:14 UTC, sebastianpfischer commented
Realizes #370