feat: Review and create new ITF unittests
eclipse/kiso-testing pull request #41
Opened 2022-04-06 15:13 UTC by TedRio

Add missing unittests, coverage is now at 90%

2022-04-11 07:08 UTC, sebclrsn approved these changes
As long as these new tests don't generate new warnings (regarding Julien's PR to delete them all), looks good to me

2022-04-11 08:54 UTC, kakooloukia requested changes

2022-04-11 08:54 UTC, kakooloukia commented on docs/whats_new/version_0_16_0.rst
> +Combined with the new flag the test execution will be stopp when something went wrong.
```suggestion
Combined with the new flag the test execution will be stopped when something go wrong.
```

2022-04-11 09:36 UTC, sebastianpfischer approved these changes

2022-04-11 09:38 UTC, sebastianpfischer commented
commit convention is also not fine

2022-04-11 09:45 UTC, kakooloukia approved these changes

2022-04-13 07:57 UTC, BKaDamien approved these changes

2022-04-22 13:42 UTC, Pog3k approved these changes

2022-04-25 07:04 UTC, Pog3k commented on tests/test_socketcan_to_trc.py
> +    class access_static_method(SocketCan2Trc):
Class is here is not necessary.

Static methods can be directly called.

SocketCan2Trc.get_type(...)

2022-04-25 07:05 UTC, Pog3k commented on tests/test_socketcan_to_trc.py
> +    assert access_static_method().get_type(can_msg) == expected_return
```suggestion
    assert SocketCan2Trc.get_type(can_msg) == expected_return
```

2022-04-25 07:22 UTC, merged

2022-04-25 07:37 UTC, Pog3k commented on tests/test_simulated_auxiliary.py
> +    class Dict_modified(dict):
class not necessary ?
Pytest gives you the tools.
mocker.patch.object(simulation.Simulation, "get_scenario", return_value=scenario.Scenario([None]))

2022-04-25 07:38 UTC, Pog3k commented on tests/test_simulated_auxiliary.py
> +    proxy_inst.context = Dict_modified()
```suggestion
    mocker.patch.object(simulation.Simulation, "get_scenario", return_value=scenario.Scenario([None]))
```

2022-04-25 07:41 UTC, Pog3k commented on tests/test_simulation.py
> +        assert simulation_inst.map_context[1, 7].pop(0) == "Test_reprun_not_implemented"
```suggestion
        assert simulation_inst.map_context[1, 7].pop(0) == "Test_report_run_not_implemented"
```

2022-04-25 07:42 UTC, Pog3k commented on tests/test_simulation.py
> +            simulation_inst.map_context[1, 11].pop(0) == "Test_notipml_report_teardown"
```suggestion
            simulation_inst.map_context[1, 11].pop(0) == "Test_not_impl_report_teardown"
```

2022-04-25 07:50 UTC, Pog3k commented on tests/test_proxy_auxiliary.py
> +    mocker.patch.object(CChannel, "open", side_effect=side_effect_value)
name could give more context - for example
```suggestion
    mocker.patch.object(CChannel, "open", side_effect=open_return_value)
```

2022-04-25 08:00 UTC, Pog3k reviewed
see my comments