fix: apply internal log level to pytest logger
eclipse/kiso-testing pull request #414
Opened 2023-11-15 15:43 UTC by sebclrsn

The refactoring of the logging mechanism broke the pytest plugin's logging configuration.

Running `pytest dummy.yaml --log-cli-level INFO -vv` now shows the INTERNAL_INFO live logs in the console

2023-11-16 06:53 UTC, sebastianpfischer requested changes
Test missing

2023-11-16 16:28 UTC, sebclrsn commented
> Test missing

Done, we now even have custom colours for our internal logs ;)

2023-11-20 08:06 UTC, Pog3k approved these changes

2023-11-20 09:05 UTC, sebastianpfischer approved these changes

2023-11-20 09:09 UTC, merged