Feat/adapt dut aux to dt aux interface
eclipse/kiso-testing pull request #77
Opened 2022-06-29 14:25 UTC by BKaDamien

-> adapt DUT auxiliary to the brand new double threaded interface
-> refactor DUT auxiliary to be more concise
-> refactor DUT Auxiliary robot version (now it fully use the pykiso code  no extra class TestEntity)
-> remove unnecessary code in test_message_handler 
-> create common behavior in dt_auxiliary interface in form of decorators (open/close connector, flash the target)
-> Refactor duplicate/unnecessary code (example_test_auxiliary)
-> create FlasherExample connector only for testing purpose  
-> adapt/rewrite all corresponding pytest

2022-06-30 15:49 UTC, sebastianpfischer requested changes
I still need to review the dut in depth

2022-06-30 15:49 UTC, sebastianpfischer commented on src/pykiso/test_setup/dynamic_loader.py
> +        # TODO: remove it after all auxes are adapted to DTAuxiliaryInterface
Can you aggregate the TODOs in one ticket please?

2022-07-01 12:52 UTC, sebastianpfischer approved these changes
Just take a look if we can improve the thread-aux interface test and then we are good to go

2022-07-04 07:00 UTC, Pog3k approved these changes

2022-07-04 13:00 UTC, merged