Add CAN connectors
eclipse/kiso-testing pull request #8
Opened 2021-12-02 09:22 UTC by kakooloukia

- Add CAN connectors
- Add Unittests

Documentation already there in connectors.rst

2021-12-02 13:28 UTC, sebastianpfischer requested changes

2021-12-02 13:28 UTC, sebastianpfischer commented on src/pykiso/lib/connectors/cc_pcan_can.py
> +# Copyright (c) 2010-2021 Robert Bosch GmbH
Nop!, wrong license used here

2021-12-02 13:28 UTC, sebastianpfischer commented on src/pykiso/lib/connectors/cc_vector_can.py
> +# Copyright (c) 2010-2021 Robert Bosch GmbH
Same here

2021-12-02 13:29 UTC, sebastianpfischer commented
Also, the doc part is missing.

2021-12-06 11:02 UTC, sebastianpfischer approved these changes

2021-12-06 13:05 UTC, sebastianpfischer commented
@kakooloukia, the jenkins is also failing

2021-12-06 14:07 UTC, Pog3k approved these changes

2021-12-07 10:12 UTC, merged