Bug fix/adapt socketcan connectors to be agnostic
eclipse/kiso-testing pull request #89
Opened 2022-07-07 08:07 UTC by BKaDamien

CCSocketCan is now agnostic

2022-07-08 07:36 UTC, Pog3k commented on src/pykiso/lib/connectors/cc_socket_can/cc_socket_can.py
> +                return {"msg": payload, "remote_id": frame_id}
adapt function type hint

2022-07-08 07:42 UTC, Pog3k commented on docs/whats_new/version_ongoing.rst
> +Agnostic CCSocketCan
The  "whats new " should actually only contain new features and not fixes. So the most interesting part for users.

You should squash everything down to one single commit message, so the changes will then appear in the Changelog.
fix: ...

2022-07-08 07:43 UTC, Pog3k requested changes
Squash commits.
Remove whats new
Update Type hint

2022-07-08 10:22 UTC, sebclrsn requested changes

2022-07-08 10:22 UTC, sebclrsn commented on tests/test_cc_socket_can.py
> +        {"msg": b"\x10\x36", "remoet_id": 0x0A, "raw": True},
```suggestion
        {"msg": b"\x10\x36", "remote_id": 0x0A, "raw": True},
```
Typo to be fixed in all parameters

2022-07-11 13:08 UTC, sebastianpfischer commented
@dependabot squash

2022-07-11 13:13 UTC, sebastianpfischer commented
Squash comes after (while merging)

2022-07-11 13:27 UTC, sebclrsn approved these changes

2022-07-11 15:39 UTC, merged