Features/step report cross domain unit test
eclipse/kiso-testing pull request #98
Opened 2022-07-14 13:07 UTC by stg2sf

2022-07-18 07:53 UTC, BKaDamien requested changes

2022-07-18 07:53 UTC, BKaDamien commented on CHANGELOG.md
> +Features:
you don't need to speciy it just respect the commit rules

2022-07-18 07:53 UTC, BKaDamien commented on CHANGELOG.md
> +Features:
In addition you have to update the pyprojecttoml with the include

2022-07-18 07:53 UTC, BKaDamien commented on setup.py
> +##########################################################################
this file is outdated and don't even exist

2022-07-19 07:55 UTC, sebastianpfischer requested changes
So from my understanding, https://github.com/eclipse/kiso-testing/pull/101 does the same no?

2022-08-11 11:29 UTC, sebastianpfischer commented
I close the PR because it is covered by #101

2022-08-11 11:29 UTC, closed without merging